[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/exam"
  to = "/.netlify/functions/api/exam"
  status = 200

[[redirects]]
  from = "/quiz"
  to = "/.netlify/functions/api/quiz"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
